*** Makefile	2015-12-09 20:01:47.553541920 +0100
--- Makefile	2015-12-09 20:11:49.820452621 +0100
***************
*** 99,108 ****
  
  AMROBJ = read_params.o init_amr.o init_time.o init_refine.o adaptive_loop.o amr_step.o update_time.o \
           output_amr.o flag_utils.o physical_boundaries.o virtual_boundaries.o refine_utils.o nbors_utils.o \
!          load_balance.o title.o units.o movie.o murmur3.o
  # Particle-Mesh objects
  PMOBJ = init_part.o output_part.o rho_fine.o synchro_fine.o move_fine.o newdt_fine.o particle_tree.o \
!         add_list.o remove_list.o cic.o
  # Poisson solver objects
  POISSONOBJ = init_poisson.o phi_fine_cg.o interpol_phi.o force_fine.o multigrid_coarse.o multigrid_fine_commons.o \
               multigrid_fine_fine.o multigrid_fine_coarse.o gravana.o boundary_potential.o rho_ana.o output_poisson.o
--- 99,108 ----
  
  AMROBJ = read_params.o init_amr.o init_time.o init_refine.o adaptive_loop.o amr_step.o update_time.o \
           output_amr.o flag_utils.o physical_boundaries.o virtual_boundaries.o refine_utils.o nbors_utils.o \
!          load_balance.o title.o units.o movie.o murmur3.o amr_tests.o
  # Particle-Mesh objects
  PMOBJ = init_part.o output_part.o rho_fine.o synchro_fine.o move_fine.o newdt_fine.o particle_tree.o \
!         add_list.o remove_list.o cic.o pm_tests.o
  # Poisson solver objects
  POISSONOBJ = init_poisson.o phi_fine_cg.o interpol_phi.o force_fine.o multigrid_coarse.o multigrid_fine_commons.o \
               multigrid_fine_fine.o multigrid_fine_coarse.o gravana.o boundary_potential.o rho_ana.o output_poisson.o
